spring.application.name=ShardedSagaWallet

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.url=jdbc:shardingsphere:classpath:sharding.yml?placeholder-type=system_props
spring.datasource.driver-class-name=org.apache.shardingsphere.driver.ShardingSphereDriver

server.port=${SERVER_PORT:3005}

sagaCompensationRetry.max-attempts=${SAGA_COMPENSATION_RETRY_MAX_ATTEMPTS}
sagaCompensationRetry.wait-duration-ms=${SAGA_COMPENSATION_RETRY_WAIT_DURATION_IN_MS}